### ISSUE TITLE
electrify fails, looking for btoa

### ISSUE THREAD

**Issue by capouch** [electrode-io/electrode-electrify#14]
I am playing around with electrify, and installed it globally, as per the README.

When I go to run it, it fails looking for module btoa:

`Error: Cannot find module 'btoa'`

I see btoa in the package.json file in the global node directory, but since btoa is set a as dev dependency it hasn't been installed.  `install btoa -g` doesn't work, nor does installing it as a module for the app I am trying to debug.

Forgive me if I'm missing something obvious.

**Comment by ananavati** [comment]
@capouch thanks for checking out electrode and electrify module, yes this looks like a bug and we are working on a fix, will publish an update soon.

**Comment by capouch** [comment]
Thanks.  I moved the btoa into the regular dependencies and it's working just fine.  I'll watch for 2.2.1.

**Comment by ananavati** [comment]
`+ electrode-electrify@2.3.0` should fix this bug. 

 @capouch Can you please verify if `v2.3.0` fixes this particular bug close out on this issue.

**Comment by capouch** [comment]
Indeed 2.3.0 installs "fine."

There is one other dependency complaint; browserify@3.46.1 -> glob@3.2.11->minimatch@0.3.0:

`npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

This is getting pretty far afield from electrify, though, and I didn't report it in the earlier message because it is a pretty common warning I see often.

**Comment by ananavati** [comment]
yeah that warning is coming up because of this 
![screen shot 2016-11-02 at 4 46 34 pm](https://cloud.githubusercontent.com/assets/360041/19951539/03eb88b0-a11c-11e6-9fdf-b049f73c35ae.png)

I will update the deps in the following days, but can we please close out this ticket since the bug has been fixed.

**Comment by capouch** [comment]
@ananavati Yes and thanks for the quick response!
