### ISSUE TITLE
Search bar not found

### ISSUE THREAD

**Issue by andypham** [electrode-io/electrode-electrify#4]
The search bar doesn't appear when click like the demo. I'm using safari browser.

**Comment by ananavati** [comment]
thanks for reporting the issue, but I am unable to reproduce on `Safari Version 10.0 (10602.1.50.0.10)`

Could please see the console and paste the JS-or-any errors here.

attached is the screenshot of my safari running `npm run demo` for `electrify`

<img width="1410" alt="screen shot 2016-09-23 at 2 17 34 pm" src="https://cloud.githubusercontent.com/assets/360041/18801619/c048cc50-8198-11e6-97ed-134867cb9662.png">

**Comment by andypham** [comment]
@ananavati I ran this command `electrify dist/server/stats.json --open`. No errors output.

<img width="1428" alt="screen shot 2016-09-23 at 2 23 18 pm" src="https://cloud.githubusercontent.com/assets/1319947/18801758/972b842e-8199-11e6-8e6e-ef42320c863b.png">

**Comment by jherr** [comment]
The code delays bringing up the search bar until all the transitions are finished. Perhaps for some reason the transitions aren't registering as finished. D3V4 has an `on('end', () => {})` built in that can reliably get the end of transition signal. Perhaps in this case we should either bring the search bar up at the end of transitions or at 4 seconds regardless. As the initial load transition is currently set to 3.25 seconds in length.

**Comment by ananavati** [comment]
@andypham 

`electrify <path-to-stats> --open` runs a bundled JS file which is part of the `npm install` and is generated as part of `prepublish` step. 

there could be 2 possible scenarios for this bug:

1. Your `electrify` install is at `v1.0.1` search feature was added after that version was published, having said that a new `MINOR` version of `electrify` was just published [v1.1.0](https://github.com/electrode-io/electrode-electrify/releases/tag/v1.1.0) with the search feature. 

2. `The code delays bringing up the search bar until all the transitions are finished. Perhaps for some reason the transitions aren't registering as finished.` as @jherr  mentioned in the previous comment.

Can you please try installing `v1.1.0`

**Comment by andypham** [comment]
@ananavati @jherr It bug occurs when place my mouse over the graph before the animation finishes. Here's the PR to fix https://github.com/electrode-io/electrode-electrify/pull/5

**Comment by ananavati** [comment]
@andypham published patch release `v1.1.1` with your pr fix https://github.com/electrode-io/electrode-electrify/pull/5 please verify.

**Comment by andypham** [comment]
@ananavati Fix verified. 👍
