### ISSUE TITLE
Error: relative path without a basedir

### ISSUE THREAD

**Issue by jantimon** [electrode-io/electrode-electrify#9]
Error: relative path without a basedir at node_modules/commondir/index.js:15:19

```
node_modules/electrode-electrify/index.js:72:14
```

My code looks like this:

```js
var disc = require('electrode-electrify');
// ...
compiler.run(function(err, stats) {
       disc.bundle(stats.toJson({
          fields:null
        }, function(err, html) {});
 });
```

I tried to debug it and saw that in node_modules/electrode-electrify/index.js:72:14

```js
var root = commondir(otherModules.map(pluck('identifier')))
```

otherModules.map(pluck('identifier')) contains also the entry point names

**Comment by ananavati** [comment]
Thanks for reporting the issue @jantimon 

Pushed the pr https://github.com/electrode-io/electrode-electrify/pull/10 to fix the issue, but would love to test the pr against your webpack-stats, Any chance you can share your webpack-stats?

**Comment by drichard** [comment]
I'm having the same issue with the just released 1.2.0. Unfortunately, I can't share my stats.json. 

```
Error: relative path without a basedir
    at /usr/local/lib/node_modules/electrode-electrify/node_modules/commondir/index.js:15:19
    at Array.reduce (native)
```

**Comment by ananavati** [comment]
sorry to hear that v1.2.0 didn't fix your issue and I totally understand that you cannot share your stats file.

The error sometimes depends on the webpack plugins used and the paths generated by that plugin. one example of a breaking path I was seeing in one of my projects:
`"identifier": "ignored /Users/ananava/walmart-oss/test-generator-electrode-component/wysiwyg-component/node_modules/intl-messageformat ./lib/locales",`

another creative way to debug your problem would be to add a `console.log("** file: ", file);` right before [line #14](https://github.com/substack/node-commondir/blob/master/index.js#L14) in `node_modules/commondir/index.js` where it throws the error inside the callback and inspect that filepath.

if possible please share that last file path before the error gets thrown.

**Comment by jantimon** [comment]
@drichard the new version has an additional bug:

```
function getBundleModules(bundles) {
  bundles = Array.isArray(bundles)
    ? bundles
    : bundles ? [bundles] : []

  if (bundles.length > 0) {
    bundles = JSON.parse(bundles.toString())
  }

  return bundles && bundles.modules // <-- bundles is an array so bundles.modules is always empty
}
```

**Comment by ritz078** [comment]
same bug for me. `throw new Error('relative path without a basedir');`

**Comment by ananavati** [comment]
unfortunately hard to debug the error without seeing the stats-json and inspecting the filepath. 

releasing a new beta version with a new file-tree parser https://github.com/electrode-io/electrode-electrify/releases/tag/v2.0.0-0

hoping the new `beta` version with a different `tree-parser` fixes the error in `commondir` module `Error: relative path without a basedir`

**Comment by jantimon** [comment]
Can you please remove the sample data from the project?
It hides so many errors. Here is the next one:

https://github.com/electrode-io/electrode-electrify/blob/2.x.x/index.js#L35

Instead of bundles you are using sample data

**Comment by ananavati** [comment]
> Can you please remove the sample data from the project?
default data was added to make it run in demo mode. default data is now passed from npm demo script.

hopefully the new file-tree parser fixes this bug. tested the new release [v2.2.0](https://github.com/electrode-io/electrode-electrify/releases/tag/v2.2.0) with the sample webpack stats object hosted on the webpack repo: https://github.com/webpack/analyse/blob/master/app/pages/upload/example.json

closing this issue as unfortunately no way to debug the issue other than look at the path inside of the webpack stats object where this particular error is being thrown.
